---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- secret.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- route.yaml

patches:

- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: rest-fights
    spec:
      template:
        spec:
          containers:
            - name: rest-fights
              image: quay.io/rh_ee_cschmitz/rest-fights-auto:2023-08-23-22-39-04

- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: rest-fights-config
    data:
      quarkus.smallrye-openapi.servers: http://rest-fights-quarkus-superheroes-user1.apps.cluster-j7tgc.sandbox986.opentlc.com
