---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- secret.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- route.yaml

patches:
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: rest-villains-config
    data:
      quarkus.smallrye-openapi.servers: http://rest-villains-quarkus-superheroes-user1.apps.cluster-j7tgc.sandbox986.opentlc.com
